### PR TITLE
Additionals minor fixes

### PR DESCRIPTION
**Pull request by gchauvet**
This pull request contains the following features :

- Upgrade version to 1.1.0 (MinGW minor feature);
- Fix issue with MinGW Windres (bad provider interface declared in mojo Annotation);
- Fix way to define the default extension used by the linker;
- Change default strategy of EnvFactoryManager

The next pull request concerns multi-executions. Current version (including 1.0 alpha 9) doesn't work correclty when trying to build the same program for 2 differents architecture.

### CODE REVIEW

**Comment by dantran** [comment]
we can get out of alpha mode and move forward to 1.0.0  but not 1.1.0

**Comment by gchauvet** [comment]
Well, ok; Maybe a beta ?  I would like to test that everything works well.
About code style, is there a ready-to-use checkstyle rules/file ?

**Comment by dantran** [comment]
maven codestyle: http://maven.apache.org/developers/conventions/code.html

yes we should have a beta

Thanks

**Comment by gchauvet** [comment]
Bump to this pull request: required for 2 others (and last !) feature submission.
Regards

**Pull request merged**
